[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    # Allow iframes from MoMo payment gateway (Safari compatibility)
    # X-Frame-Options = "DENY" - REMOVED to allow embedding MoMo iframe
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "no-referrer-when-downgrade"
    Permissions-Policy = "camera=*, microphone=*, payment=*"